spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_db  # Replace with your database URL
    username: your-username                      # Replace with your database username
    password: your-password                      # Replace with your database password
  jpa:
    hibernate:
      ddl-auto: update  # Use 'update' to automatically create/update the database schema
    show-sql: true      # Set to true to display SQL queries in the console
